import { Schema, type Document } from "mongoose";
import { defineModel } from "@/lib/mongoose-model";

export interface ITokenUsage extends Document {
  userId: string;
  username: string;
  /** Denormalized display name of the user at the time of the request. */
  displayName?: string | null;
  /** Denormalized role of the user, so teacher usage can be split from student usage. */
  role?: string | null;
  /**
   * Denormalized school id (stringified ObjectId) the user belonged to at the
   * time of the request. Null for admins / users without a school.
   *
   * Denormalized on purpose: usage reports must stay accurate even after a user
   * is moved between schools or deleted, and it keeps the admin aggregations
   * free of a per-document $lookup.
   */
  schoolId?: string | null;
  /** Denormalized school name at the time of the request. */
  schoolName?: string | null;
  /** Which subject/feature triggered this request */
  subject: string;
  /**
   * The specific learning activity within the subject (e.g. "lin-zexu",
   * "reading-comprehension"). See lib/usage-topics.ts for the registry.
   */
  topic?: string | null;
  /** The model/deployment used */
  modelName: string;
  /**
   * Non-cached prompt (input) tokens. This EXCLUDES cached tokens — it is the
   * portion of the input billed at the full input rate. Add cachedInputTokens
   * to get the total input tokens Azure reported.
   */
  promptTokens: number;
  /**
   * Cached input tokens (input served from the provider's prompt cache, billed
   * at the discounted cache rate). Mutually exclusive with promptTokens;
   * promptTokens + cachedInputTokens = total input tokens.
   */
  cachedInputTokens: number;
  /** Tokens generated by the completion (output) */
  completionTokens: number;
  /** Total tokens (prompt + completion) */
  totalTokens: number;
  /**
   * Tokens consumed by RAG retrieval embeddings (embedding the student query
   * before querying the vector store). 0 when the request did not use RAG.
   * Billed separately from chat tokens (embedding model, not the chat model).
   */
  ragTokens: number;
  /** Optional: the associated chat session ID */
  chatId?: string;
  /** Optional: the API route that handled the request */
  endpoint: string;
  createdAt: Date;
}

const TokenUsageSchema = new Schema<ITokenUsage>(
  {
    userId: { type: String, required: true, index: true },
    username: { type: String, required: true },
    displayName: { type: String, default: null },
    role: { type: String, default: null },
    schoolId: { type: String, default: null, index: true },
    schoolName: { type: String, default: null },
    subject: { type: String, required: true, index: true },
    topic: { type: String, default: null, index: true },
    modelName: { type: String, required: true },
    promptTokens: { type: Number, required: true, default: 0 },
    cachedInputTokens: { type: Number, required: true, default: 0 },
    completionTokens: { type: Number, required: true, default: 0 },
    totalTokens: { type: Number, required: true, default: 0 },
    ragTokens: { type: Number, required: true, default: 0 },
    chatId: { type: String },
    endpoint: { type: String, required: true },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

TokenUsageSchema.index({ createdAt: -1 });
TokenUsageSchema.index({ userId: 1, createdAt: -1 });
TokenUsageSchema.index({ subject: 1, createdAt: -1 });
// Admin analytics access patterns: filter by school (and optionally subject)
// over a date range, or drill into a single topic.
TokenUsageSchema.index({ schoolId: 1, createdAt: -1 });
TokenUsageSchema.index({ schoolId: 1, subject: 1, createdAt: -1 });
TokenUsageSchema.index({ topic: 1, createdAt: -1 });

export const TokenUsage = defineModel<ITokenUsage>("TokenUsage", TokenUsageSchema);
